import { PERMISSIONS } from "./permissions.ts";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
	owner: [
		// Permissões de usuários
		PERMISSIONS.USERS_VIEW,
		PERMISSIONS.USERS_CREATE,
		PERMISSIONS.USERS_EDIT,
		PERMISSIONS.USERS_DELETE,
		PERMISSIONS.USERS_DELETE_ADMIN,
		PERMISSIONS.USERS_CHANGE_ROLE,
		PERMISSIONS.USERS_INVITE,

		// Permissões de tenant (exclusivas do owner)
		PERMISSIONS.TENANT_VIEW,
		PERMISSIONS.TENANT_EDIT,
		PERMISSIONS.TENANT_DELETE,
		PERMISSIONS.TENANT_TRANSFER_OWNERSHIP,
		PERMISSIONS.TENANT_MANAGE_BILLING,
		PERMISSIONS.TENANT_MANAGE_PLAN,

		// Permissões de chatbots
		PERMISSIONS.BOTS_VIEW,
		PERMISSIONS.BOTS_CREATE,
		PERMISSIONS.BOTS_EDIT,
		PERMISSIONS.BOTS_DELETE,
		PERMISSIONS.BOTS_CONFIGURE,
		PERMISSIONS.BOTS_ADJUST_PROMPTS,

		// Permissões de conhecimento
		PERMISSIONS.KNOWLEDGE_VIEW,
		PERMISSIONS.KNOWLEDGE_CREATE,
		PERMISSIONS.KNOWLEDGE_EDIT,
		PERMISSIONS.KNOWLEDGE_DELETE,
		PERMISSIONS.KNOWLEDGE_MANAGE_SOURCES,
		PERMISSIONS.KNOWLEDGE_ADJUST_RETRIEVAL,

		// Permissões de conversas
		PERMISSIONS.CONVERSATIONS_VIEW,
		PERMISSIONS.CONVERSATIONS_VIEW_OWN,
		PERMISSIONS.CONVERSATIONS_TAKEOVER,
		PERMISSIONS.CONVERSATIONS_PROVIDE_FEEDBACK,

		// Permissões de analytics
		PERMISSIONS.ANALYTICS_VIEW_ALL,
		PERMISSIONS.ANALYTICS_VIEW_LIMITED,

		// Permissões de integrações
		PERMISSIONS.INTEGRATIONS_MANAGE,
		PERMISSIONS.INTEGRATIONS_RAGFLOW,
	],

	// Admin: pode fazer quase tudo, exceto ações exclusivas do owner
	admin: [
		// Permissões de usuários
		PERMISSIONS.USERS_VIEW,
		PERMISSIONS.USERS_CREATE,
		PERMISSIONS.USERS_EDIT,
		PERMISSIONS.USERS_DELETE,
		PERMISSIONS.USERS_CHANGE_ROLE,
		PERMISSIONS.USERS_INVITE,

		// Permissões de tenant (limitadas)
		PERMISSIONS.TENANT_VIEW,
		PERMISSIONS.TENANT_EDIT,

		// Permissões de chatbots
		PERMISSIONS.BOTS_VIEW,
		PERMISSIONS.BOTS_CREATE,
		PERMISSIONS.BOTS_EDIT,
		PERMISSIONS.BOTS_DELETE,
		PERMISSIONS.BOTS_CONFIGURE,
		PERMISSIONS.BOTS_ADJUST_PROMPTS,

		// Permissões de conhecimento
		PERMISSIONS.KNOWLEDGE_VIEW,
		PERMISSIONS.KNOWLEDGE_CREATE,
		PERMISSIONS.KNOWLEDGE_EDIT,
		PERMISSIONS.KNOWLEDGE_DELETE,
		PERMISSIONS.KNOWLEDGE_MANAGE_SOURCES,
		PERMISSIONS.KNOWLEDGE_ADJUST_RETRIEVAL,

		// Permissões de conversas
		PERMISSIONS.CONVERSATIONS_VIEW,
		PERMISSIONS.CONVERSATIONS_VIEW_OWN,
		PERMISSIONS.CONVERSATIONS_TAKEOVER,
		PERMISSIONS.CONVERSATIONS_PROVIDE_FEEDBACK,

		// Permissões de analytics
		PERMISSIONS.ANALYTICS_VIEW_ALL,

		// Permissões de integrações
		PERMISSIONS.INTEGRATIONS_MANAGE,
		PERMISSIONS.INTEGRATIONS_RAGFLOW,
	],

	// Curator: foco em gerenciar conhecimento e ajustar chatbots
	curator: [
		// Permissões de usuários (limitadas)
		PERMISSIONS.USERS_VIEW,

		// Permissões de tenant (apenas visualização)
		PERMISSIONS.TENANT_VIEW,

		// Permissões de chatbots (sem criar/excluir)
		PERMISSIONS.BOTS_VIEW,
		PERMISSIONS.BOTS_EDIT,
		PERMISSIONS.BOTS_CONFIGURE,
		PERMISSIONS.BOTS_ADJUST_PROMPTS,

		// Permissões de conhecimento (foco principal)
		PERMISSIONS.KNOWLEDGE_VIEW,
		PERMISSIONS.KNOWLEDGE_CREATE,
		PERMISSIONS.KNOWLEDGE_EDIT,
		PERMISSIONS.KNOWLEDGE_DELETE,
		PERMISSIONS.KNOWLEDGE_MANAGE_SOURCES,
		PERMISSIONS.KNOWLEDGE_ADJUST_RETRIEVAL,

		// Permissões de conversas
		PERMISSIONS.CONVERSATIONS_VIEW,
		PERMISSIONS.CONVERSATIONS_VIEW_OWN,
		PERMISSIONS.CONVERSATIONS_TAKEOVER,
		PERMISSIONS.CONVERSATIONS_PROVIDE_FEEDBACK,

		// Permissões de analytics (limitadas)
		PERMISSIONS.ANALYTICS_VIEW_LIMITED,
	],

	// User: permissões básicas para usar o sistema
	user: [
		// Permissões de chatbots (apenas visualização)
		PERMISSIONS.BOTS_VIEW,

		// Permissões de conhecimento (apenas visualização)
		PERMISSIONS.KNOWLEDGE_VIEW,

		// Permissões de conversas (próprias)
		PERMISSIONS.CONVERSATIONS_VIEW_OWN,
		PERMISSIONS.CONVERSATIONS_PROVIDE_FEEDBACK,
	],
};
